language: csharp
mono: none
dotnet: 2.0.2
services:
  - docker
script:
 - dotnet test ./test/UnitTest/InsuranceQuotePortal.Webapp.Test/InsuranceQuotePortal.Webapp.Test.csproj
after_success:
  - test "$TRAVIS_BRANCH" = "master" && sh scripts/deploy_heroku.sh