version: '3.3'

services: 
    
  insurancequoteportal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"