// <auto-generated />
using InsuranceQuotePortal.Domain.Models;
using InsuranceQuotePortal.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace InsuranceQuotePortal.Webapp.Infrastructure.Migrations
{
    [DbContext(typeof(QuotingContext))]
    [Migration("20180302160823_QuoteContext")]
    partial class QuoteContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsuranceQuotePortal.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<double>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("InsuranceQuotePortal.Domain.Models.CustumerInsuranceProveded", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<int>("InsuranceProvided");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustumerInsuranceProveded");
                });

            modelBuilder.Entity("InsuranceQuotePortal.Domain.Models.CustumerInsuranceProveded", b =>
                {
                    b.HasOne("InsuranceQuotePortal.Domain.Models.Customer")
                        .WithMany("InsuranceProvided")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
